#!/usr/bin/env python3
"""Generate a differential-test corpus for the Kotlin centerline port.

Runs the ORIGINAL Jython module (pure math, python3-safe) over pseudo-random
and degenerate border pairs and writes input/expected pairs consumed by
CenterlineCorpusTest. Regenerate only if the original changes:

    python3 testdata/centerline/gen_centerline_corpus.py

Determinism comes from a fixed seed, so reruns produce an identical corpus.
"""

import os
import random
import sys

ORIGINAL = "/ll2_tooling_root/JOSM_lanelet2_editing_scripts/core/infra"
sys.path.insert(0, ORIGINAL)

import lanelet2_centerline_calculate as ll2  # noqa: E402

OUT = os.path.join(
    os.path.dirname(os.path.abspath(__file__)),
    "..", "..", "plugin-core", "src", "test", "resources", "centerline-corpus.txt",
)

SEED = 20260908


def fmt_pts(pts):
    return ";".join("%r,%r" % (p[0], p[1]) for p in pts)


def parallel_borders(rng, n, width, jitter, curve):
    """Typical lanelet: two roughly parallel polylines in driving direction."""
    left, right = [], []
    for i in range(n):
        t = float(i)
        lon = t * 0.0001 + rng.uniform(-jitter, jitter)
        lat = curve * t * t * 0.00001 + rng.uniform(-jitter, jitter)
        left.append((lon, lat + width))
        right.append((lon + rng.uniform(-jitter, jitter), lat))
    return left, right


def build_cases():
    rng = random.Random(SEED)
    cases = []

    # Typical parallel borders, varying length / width / jitter / curvature.
    for _ in range(90):
        n = rng.randint(2, 9)
        cases.append(parallel_borders(
            rng, n,
            width=rng.uniform(0.00002, 0.0004),
            jitter=rng.uniform(0.0, 0.00003),
            curve=rng.uniform(-3.0, 3.0),
        ))

    # Unequal border lengths (the Python never enforced equal size).
    for _ in range(40):
        left, _ = parallel_borders(rng, rng.randint(2, 8), 0.0002, 0.00002, 1.0)
        _, right = parallel_borders(rng, rng.randint(2, 8), 0.0002, 0.00002, -1.0)
        cases.append((left, right))

    # Shared start point (drives the li = 1 branch).
    for _ in range(15):
        left, right = parallel_borders(rng, rng.randint(3, 7), 0.0002, 0.00001, 0.5)
        right[0] = left[0]
        cases.append((left, right))

    # Shared end point.
    for _ in range(15):
        left, right = parallel_borders(rng, rng.randint(3, 7), 0.0002, 0.00001, 0.5)
        right[-1] = left[-1]
        cases.append((left, right))

    # Duplicate consecutive vertices.
    for _ in range(15):
        left, right = parallel_borders(rng, rng.randint(3, 7), 0.0002, 0.00001, 0.0)
        i = rng.randrange(len(left))
        left.insert(i, left[i])
        cases.append((left, right))

    # Reversed right border (misaligned bounds -> the bail-out path).
    for _ in range(15):
        left, right = parallel_borders(rng, rng.randint(3, 7), 0.0002, 0.00001, 0.0)
        cases.append((left, list(reversed(right))))

    # Identical borders (zero width).
    for _ in range(10):
        left, _ = parallel_borders(rng, rng.randint(2, 6), 0.0002, 0.0, 0.0)
        cases.append((left, list(left)))

    # Crossing / self-intersecting bounds.
    for _ in range(20):
        n = rng.randint(3, 7)
        left, right = parallel_borders(rng, n, 0.0002, 0.00001, 0.0)
        i, j = rng.randrange(n), rng.randrange(n)
        left[i], right[j] = right[j], left[i]
        cases.append((left, right))

    # Hand-picked structural edge cases.
    cases += [
        ([(0.0, 1.0)], [(0.0, 0.0)]),
        ([(0.0, 1.0), (1.0, 1.0)], [(0.0, 0.0), (1.0, 0.0)]),
        ([(0.0, 0.0)], [(0.0, 0.0)]),
        ([(0.0, 1.0), (1.0, 1.0), (2.0, 1.0)], [(0.0, 0.0), (2.0, 0.0)]),
        ([(0.0, 1.0), (1.0, 1.0)], [(0.0, 0.0), (1.0, 0.0), (2.0, 0.0)]),
        ([(0.0, 0.0), (1.0, 0.0)], [(1.0, 0.0), (0.0, 0.0)]),
        ([(0.0, 1.0), (0.0, 1.0), (1.0, 1.0)], [(0.0, 0.0), (1.0, 0.0)]),
        ([(-0.5, 0.25), (0.5, 0.25)], [(-0.5, -0.25), (0.5, -0.25)]),
    ]
    return cases


def main():
    cases = build_cases()
    out_path = os.path.abspath(OUT)
    lines = [
        "# Differential corpus: expected values produced by the original",
        "# core/infra/lanelet2_centerline_calculate.py. Generated by",
        "# testdata/centerline/gen_centerline_corpus.py (seed %d). Do not hand-edit." % SEED,
    ]
    for left, right in cases:
        expected = ll2.calculate_centerline_points(left, right)
        lines.append("%s|%s|%s" % (fmt_pts(left), fmt_pts(right), fmt_pts(expected)))

    with open(out_path, "w") as fh:
        fh.write("\n".join(lines) + "\n")

    total_pts = sum(len(l) + len(r) for l, r in cases)
    print("wrote %d cases (%d border points) to %s" % (len(cases), total_pts, out_path))


if __name__ == "__main__":
    main()
