package org.openstreetmap.josm.plugins.lanelet2.edit

import org.openstreetmap.josm.plugins.lanelet2.platform.ActionRegistry
import org.openstreetmap.josm.plugins.lanelet2.platform.ActionSlot
import org.openstreetmap.josm.plugins.lanelet2.platform.LaneletAction
import org.openstreetmap.josm.plugins.lanelet2.platform.MenuId
import java.awt.event.ActionEvent

/**
 * Registers batch-A lanelet_edit actions into [ActionRegistry].
 *
 * Call [registerAll] from [org.openstreetmap.josm.plugins.lanelet2.Lanelet2Plugin]
 * during plugin construction, **before** menus are installed (at startup, not
 * when the first data layer opens). Batch B should add a sibling object (e.g. `SmoothSplitActions`) with
 * its own `registerAll()` and invoke it from the same plugin `init` block —
 * do not edit this file to add those slots.
 *
 * Slot ids are the canonical strings from [ActionRegistry.BASE_UTILS_ORDER] /
 * [ActionRegistry.BASE_MAP_ORDER]. Metadata matches `launcher/registry.py`.
 */
object EditActions {
    /** Slot id plus which menu it belongs to. Used by tests to catch typos. */
    val SLOT_SPECS: List<Pair<String, MenuId>> = listOf(
        "lanelet_edit.check_lanelet_borders" to MenuId.UTILS,
        "lanelet_edit.merge_lanelets_swapped_borders" to MenuId.UTILS,
        "lanelet_edit.add_reg_elem_to_lanelets" to MenuId.MAP,
        "lanelet_edit.merge_shared_border_lanelets" to MenuId.MAP,
        "lanelet_edit.revert_lanelet_direction" to MenuId.MAP,
        "lanelet_edit.delete_relations_with_membership_removal" to MenuId.MAP,
        "lanelet_edit.purge_relations_with_members" to MenuId.MAP,
    )

    fun registerAll(registry: ActionRegistry = ActionRegistry.INSTANCE) {
        for (slot in allSlots()) {
            registry.register(slot)
        }
    }

    fun allSlots(): List<ActionSlot> = listOf(
        slot(
            id = "lanelet_edit.check_lanelet_borders",
            displayName = "Check Lanelet Borders (select broken)",
            shortcutKey = "B",
            toolbarLabel = "Chk Bord",
            iconPath = "icons/check_borders.svg",
            menu = MenuId.UTILS,
        ) { CheckLaneletBorders.run() },
        slot(
            id = "lanelet_edit.merge_lanelets_swapped_borders",
            displayName = "Merge lanelets (same bounds, swapped left/right)",
            shortcutKey = null,
            toolbarLabel = null,
            iconPath = null,
            menu = MenuId.UTILS,
        ) { MergeSwappedBorders.run() },
        slot(
            id = "lanelet_edit.add_reg_elem_to_lanelets",
            displayName = "Add Regulatory Element to Lanelets",
            shortcutKey = "A",
            toolbarLabel = "Add RegE",
            iconPath = "icons/add_reg_elem.svg",
            menu = MenuId.MAP,
        ) { AddRegElemToLanelets.run() },
        slot(
            id = "lanelet_edit.merge_shared_border_lanelets",
            displayName = "Merge Shared Border (2 lanelets)",
            shortcutKey = "8",
            toolbarLabel = "Merge",
            iconPath = "icons/merge_border.svg",
            menu = MenuId.MAP,
        ) { MergeSharedBorder.run() },
        slot(
            id = "lanelet_edit.revert_lanelet_direction",
            displayName = "Revert Lanelet Direction",
            shortcutKey = "R",
            toolbarLabel = "Rev",
            iconPath = "icons/revert_dir.svg",
            menu = MenuId.MAP,
        ) { RevertLaneletDirection.run() },
        slot(
            id = "lanelet_edit.delete_relations_with_membership_removal",
            displayName = "Delete Relations (with membership removal)",
            shortcutKey = "D",
            toolbarLabel = "Del Rel",
            iconPath = "icons/delete_rels.svg",
            menu = MenuId.MAP,
        ) { DeleteRelations.run() },
        slot(
            id = "lanelet_edit.purge_relations_with_members",
            displayName = "Purge Relations (incl. member ways & nodes)",
            shortcutKey = "U",
            toolbarLabel = "Purge",
            iconPath = "icons/purge.svg",
            menu = MenuId.MAP,
        ) { PurgeRelations.run() },
    )

    private fun slot(
        id: String,
        displayName: String,
        shortcutKey: String?,
        toolbarLabel: String?,
        iconPath: String?,
        menu: MenuId,
        run: () -> Unit,
    ): ActionSlot {
        val action = object : LaneletAction(displayName, iconPath, displayName, shortcutKey) {
            override fun actionPerformed(e: ActionEvent) = run()
        }
        return ActionSlot(
            id = id,
            action = action,
            toolbarLabel = toolbarLabel,
            iconName = iconPath,
            menu = menu,
        )
    }
}
