package org.openstreetmap.josm.plugins.lanelet2.tools

import org.junit.jupiter.api.Assertions.assertEquals
import org.junit.jupiter.api.Assertions.assertTrue
import org.junit.jupiter.api.BeforeEach
import org.junit.jupiter.api.Test
import org.openstreetmap.josm.plugins.lanelet2.infra.OsmFixtures
import org.openstreetmap.josm.plugins.lanelet2.platform.LaneletSettings
import org.openstreetmap.josm.spi.preferences.Config
import org.openstreetmap.josm.spi.preferences.MemoryPreferences

/**
 * Hull numbers are pinned against a CPython replica of
 * `highlight_file_boundaries.py` (insertion-ordered sets, same constants).
 */
class HighlightFileBoundariesTest {

    @BeforeEach
    fun setUp() {
        Config.setPreferencesInstance(MemoryPreferences())
    }

    @Test
    fun paletteMatchesJythonHsv() {
        assertEquals("#f2bc54", FileBoundaryHull.hsvToHex(0.11, 0.65, 0.95))
        assertEquals("#f25454", FileBoundaryHull.hsvToHex(0.0, 0.65, 0.95))
        assertEquals(
            listOf("#f2bc54", "#8e54f2", "#54f260", "#f25476", "#54a4f2"),
            FileBoundaryHull.palette(5),
        )
    }

    @Test
    fun chooseCellHonoursMinAndMaxCellsCap() {
        assertEquals(60.0, FileBoundaryHull.chooseCell(0.0, 0.0, 10.0, 10.0, 60.0), 0.0)
        assertEquals(0.5, FileBoundaryHull.chooseCell(0.0, 0.0, 10.0, 10.0, 0.1), 0.0)
        assertEquals(40.82503317053153, FileBoundaryHull.chooseCell(0.0, 0.0, 100_000.0, 100_000.0, 0.5), 1e-12)
    }

    @Test
    fun occupiedDilateFillAndDpMatchJythonReplica() {
        val pts = lShapePlusBlob()
        val minE = 0.0
        val minN = 0.0
        val cell = 10.0
        val occ = FileBoundaryHull.occupiedCells(pts, minE, minN, cell)
        assertEquals(
            setOf(
                0 to 0, 0 to 1, 0 to 2, 0 to 3, 0 to 4,
                1 to 0, 2 to 0, 3 to 0, 4 to 0,
                8 to 8, 8 to 9, 8 to 10,
                9 to 8, 9 to 9, 9 to 10,
                10 to 8, 10 to 9, 10 to 10,
            ),
            occ.toSet(),
        )
        val dil = FileBoundaryHull.dilate(occ, FileBoundaryHull.DILATE_R)
        assertEquals(114, dil.size)
        val filled = FileBoundaryHull.fillHoles(dil)
        assertEquals(dil.toSet(), filled.toSet())

        val stair = listOf(0 to 0, 1 to 0, 2 to 0, 2 to 1, 2 to 2)
        assertEquals(listOf(0 to 0, 2 to 0, 2 to 2), FileBoundaryHull.dpSimplify(stair, 1.3))
        assertEquals(listOf(0 to 0, 1 to 0), FileBoundaryHull.dpSimplify(listOf(0 to 0, 1 to 0), 1.3))
        assertEquals(1.0, FileBoundaryHull.pointSegDist2(1.0 to 1.0, 0.0 to 0.0, 2.0 to 0.0), 1e-12)
        assertEquals(1.0, FileBoundaryHull.pointSegDist2(3.0 to 0.0, 0.0 to 0.0, 2.0 to 0.0), 1e-12)
        assertEquals(2.0, FileBoundaryHull.pointSegDist2(1.0 to 1.0, 0.0 to 0.0, 0.0 to 0.0), 1e-12)
    }

    @Test
    fun fillHolesClosesInteriorOfSquareRing() {
        val border = LinkedHashSet<Pair<Int, Int>>()
        for (x in 0..4) {
            for (y in 0..4) {
                if (x == 0 || x == 4 || y == 0 || y == 4) border.add(x to y)
            }
        }
        val filled = FileBoundaryHull.fillHoles(border)
        assertEquals(25, filled.size)
        val interior = (filled - border).sortedWith(compareBy({ it.first }, { it.second }))
        assertEquals(
            listOf(
                1 to 1, 1 to 2, 1 to 3,
                2 to 1, 2 to 2, 2 to 3,
                3 to 1, 3 to 2, 3 to 3,
            ),
            interior,
        )
    }

    @Test
    fun hullRingsMatchJythonReplica() {
        val pts = lShapePlusBlob()
        val hulls = FileBoundaryHull.hullRingsFor(pts, 0.0, 0.0, 10.0)
        assertEquals(2, hulls.size)
        // Insertion-ordered replica of the Jython pipeline (LinkedHashSet / CPython 3.7+ dict).
        assertPts(
            listOf(
                -20.0 to -20.0, 70.0 to -20.0, 70.0 to 30.0, 30.0 to 30.0,
                30.0 to 70.0, -20.0 to 70.0, -20.0 to -10.0,
            ),
            hulls[0],
        )
        assertPts(
            listOf(60.0 to 60.0, 130.0 to 60.0, 130.0 to 130.0, 60.0 to 130.0, 60.0 to 70.0),
            hulls[1],
        )
    }

    @Test
    fun generateMapcssKeepsJythonCommentAndOpacity() {
        val css = FileBoundaryHull.generateMapcss(listOf("a/b/foo.osm", "other"), FileBoundaryHull.palette(2))
        assertTrue(css.startsWith("/* Auto-generated by highlight_file_boundaries.py - do not edit. */"))
        assertTrue("title: \"Lanelet2 File Boundaries\"" in css)
        assertTrue("fill-opacity: 0.16" in css)
        assertTrue("ll2_bnd=\"0\"" in css)
        assertTrue("#f2bc54" in css)
        assertTrue("#8e54f2" in css)
    }

    @Test
    fun mismatchesUseLiteralFileOriginNotGroupTagAndStringSortIds() {
        LaneletSettings.setHighlightGroupTag("source_file")
        val wayA = OsmFixtures.way(0.0 to 0.0, 1.0 to 0.0)
        wayA.put("file_origin", "b.osm")
        val wayB = OsmFixtures.way(0.0 to 1.0, 1.0 to 1.0)
        val rel10 = OsmFixtures.relation("lanelet", members = arrayOf("left" to wayA))
        rel10.put("file_origin", "a.osm")
        val rel9 = OsmFixtures.relation("multipolygon", members = arrayOf("outer" to wayB))
        rel9.put("file_origin", "a.osm")
        val skipped = OsmFixtures.relation("lanelet", members = arrayOf("left" to wayA))
        skipped.put("source_file", "a.osm")
        val ds = OsmFixtures.dataSet(rel10, rel9, skipped)
        val rows = HighlightFileBoundaries.findRelationOriginMismatches(ds)
        assertEquals(2, rows.size)
        assertEquals("lanelet", rows[0].type)
        assertEquals("multipolygon", rows[1].type)
        assertEquals(listOf("b.osm"), rows[0].memberFos)
        assertEquals(listOf(HighlightFileBoundaries.UNTAGGED_ORIGIN), rows[1].memberFos)
        assertTrue(rows.none { it.rel === skipped }, "parent without file_origin must be skipped")
        assertEquals("file_origin", HighlightFileBoundaries.FILE_ORIGIN_TAG)
        assertEquals("source_file", HighlightFileBoundaries.groupTag())
    }

    @Test
    fun originBasenameAndLayerStem() {
        assertEquals("foo.osm", HighlightFileBoundaries.originBasename("/maps/foo.osm"))
        assertEquals(
            HighlightFileBoundaries.UNTAGGED_ORIGIN,
            HighlightFileBoundaries.originBasename(HighlightFileBoundaries.UNTAGGED_ORIGIN),
        )
        assertEquals("city", HighlightFileBoundaries.layerStemFrom("city.osm", "ignored.osm"))
        assertEquals("notes", HighlightFileBoundaries.layerStemFrom("notes", "x.osm"))
        assertEquals("map", HighlightFileBoundaries.layerStemFrom(null, ""))
        assertEquals("map", HighlightFileBoundaries.layerStemFrom(null, null))
        assertEquals("layer", HighlightFileBoundaries.layerStemFrom(null, "layer.osm"))
    }

    @Test
    fun groupTagFallsBackWhenEmpty() {
        assertEquals("file_origin", LaneletSettings.getHighlightGroupTag())
        LaneletSettings.setHighlightGroupTag("  ")
        assertEquals("file_origin", LaneletSettings.getHighlightGroupTag())
        LaneletSettings.put(LaneletSettings.KEY_HIGHLIGHT_GROUP_TAG, "")
        assertEquals("file_origin", LaneletSettings.getHighlightGroupTag())
        LaneletSettings.setHighlightGroupTag("custom")
        assertEquals("custom", LaneletSettings.getHighlightGroupTag())
    }

    @Test
    fun matchingMemberIsNotAMismatch() {
        val way = OsmFixtures.way(0.0 to 0.0, 1.0 to 0.0)
        way.put("file_origin", "a.osm")
        val rel = OsmFixtures.relation("lanelet", members = arrayOf("left" to way))
        rel.put("file_origin", "a.osm")
        val ds = OsmFixtures.dataSet(rel)
        assertTrue(HighlightFileBoundaries.findRelationOriginMismatches(ds).isEmpty())
    }

    @Test
    fun mismatchIdsAreStringSortedNotNumeric() {
        val w1 = OsmFixtures.way(0.0 to 0.0, 1.0 to 0.0)
        val w2 = OsmFixtures.way(0.0 to 1.0, 1.0 to 1.0)
        val rA = OsmFixtures.relation("lanelet", members = arrayOf("left" to w1))
        rA.put("file_origin", "p.osm")
        val rB = OsmFixtures.relation("lanelet", members = arrayOf("left" to w2))
        rB.put("file_origin", "p.osm")
        OsmFixtures.dataSet(rA, rB)
        val rows = listOf(
            HighlightFileBoundaries.OriginMismatch(rA, "lanelet", "10", "p.osm", listOf("<untagged>")),
            HighlightFileBoundaries.OriginMismatch(rB, "lanelet", "9", "p.osm", listOf("<untagged>")),
        ).sortedWith(compareBy({ it.type }, { it.id }))
        assertEquals(listOf("10", "9"), rows.map { it.id })
    }

    private fun lShapePlusBlob(): List<Pair<Double, Double>> {
        val pts = ArrayList<Pair<Double, Double>>()
        var e = 0
        while (e <= 40) {
            pts.add(e.toDouble() to 0.0)
            e += 5
        }
        var n = 5
        while (n <= 40) {
            pts.add(0.0 to n.toDouble())
            n += 5
        }
        e = 80
        while (e <= 100) {
            n = 80
            while (n <= 100) {
                pts.add(e.toDouble() to n.toDouble())
                n += 5
            }
            e += 5
        }
        return pts
    }

    private fun assertPts(expected: List<Pair<Double, Double>>, actual: List<Pair<Double, Double>>) {
        assertEquals(expected.size, actual.size, "size expected=$expected actual=$actual")
        for (i in expected.indices) {
            assertEquals(expected[i].first, actual[i].first, 1e-12, "e[$i]")
            assertEquals(expected[i].second, actual[i].second, 1e-12, "n[$i]")
        }
    }

    private infix fun Int.to(n: Int) = Pair(this, n)
    private infix fun Double.to(n: Double) = Pair(this, n)
}
