package org.openstreetmap.josm.plugins.lanelet2.notes

/**
 * Inline MapCSS generator from `notes_core.generate_mapcss`. Preset type
 * rules are emitted in [NotesTags.TYPE_COLORS] insertion order; extra types
 * are sorted. The header comment is the Jython string verbatim.
 */
fun hsvToHex(h: Double, s: Double, v: Double): String {
    var i = (h * 6.0).toInt()
    val f = h * 6.0 - i
    val p = v * (1.0 - s)
    val q = v * (1.0 - f * s)
    val t = v * (1.0 - (1.0 - f) * s)
    i %= 6
    if (i < 0) i += 6
    val (r, g, b) = when (i) {
        0 -> Triple(v, t, p)
        1 -> Triple(q, v, p)
        2 -> Triple(p, v, t)
        3 -> Triple(p, q, v)
        4 -> Triple(t, p, v)
        else -> Triple(v, p, q)
    }
    return "#%02x%02x%02x".format((r * 255).toInt(), (g * 255).toInt(), (b * 255).toInt())
}

fun colorForType(noteTypeValue: String, extraIndex: Int): String {
    val preset = NotesTags.TYPE_COLORS[noteTypeValue]
    if (preset != null) return preset
    if (extraIndex < 0) return NotesTags.DEFAULT_COLOR
    return hsvToHex((0.11 + extraIndex * 0.6180339887) % 1.0, 0.7, 0.95)
}

fun generateMapCss(discoveredTypes: Collection<String> = emptyList()): String {
    val types = LinkedHashSet(NotesTags.NOTE_TYPES)
    types.addAll(discoveredTypes.filter { it.isNotEmpty() })
    val extra = types.filter { it !in NotesTags.TYPE_COLORS }.sorted()

    val lines = ArrayList<String>()
    lines.add("/* Auto-generated by notes_core.py - do not edit. */")
    lines.add("meta { title: \"${NotesTags.STYLE_TITLE}\"; }")
    lines.add(
        "node[${NotesTags.TAG_ANCHOR}] { symbol-shape: circle; symbol-size: 14; " +
            "symbol-fill-color: ${NotesTags.DEFAULT_COLOR}; symbol-stroke-color: white; " +
            "symbol-stroke-width: 2; text: tag(\"${NotesTags.TAG_TEXT}\"); text-color: ${NotesTags.DEFAULT_COLOR}; " +
            "text-offset-x: 8; font-size: ${NotesTags.NOTE_FONT_SIZE}; font-weight: bold; z-index: 1000; }",
    )
    lines.add(
        "node[${NotesTags.TAG_MEMBER}] { symbol-shape: circle; symbol-size: 5; " +
            "symbol-fill-color: ${NotesTags.DEFAULT_COLOR}; symbol-stroke-color: ${NotesTags.DEFAULT_COLOR}; " +
            "symbol-stroke-width: 1; opacity: 0.55; z-index: 900; }",
    )
    lines.add(
        "way[${NotesTags.TAG_MARKER}] { color: ${NotesTags.DEFAULT_COLOR}; width: 3; " +
            "fill-color: ${NotesTags.DEFAULT_COLOR}; fill-opacity: 0.12; z-index: 900; }",
    )

    fun addType(t: String, idx: Int) {
        val c = colorForType(t, idx)
        lines.add(
            "node[${NotesTags.TAG_ANCHOR}][${NotesTags.TAG_TYPE}=\"$t\"] { " +
                "symbol-fill-color: $c; symbol-stroke-color: $c; }",
        )
        lines.add(
            "node[${NotesTags.TAG_MEMBER}][${NotesTags.TAG_TYPE}=\"$t\"] { " +
                "symbol-fill-color: $c; symbol-stroke-color: $c; }",
        )
        lines.add(
            "way[${NotesTags.TAG_MARKER}][${NotesTags.TAG_TYPE}=\"$t\"] { color: $c; fill-color: $c; }",
        )
    }

    for (t in NotesTags.TYPE_COLORS.keys) addType(t, -1)
    extra.forEachIndexed { i, t -> addType(t, i) }

    for (sev in NotesTags.SEVERITIES) {
        lines.add(
            "node[${NotesTags.TAG_ANCHOR}][${NotesTags.TAG_SEVERITY}=\"$sev\"] { " +
                "symbol-size: ${NotesTags.SEVERITY_SIZE[sev]}; }",
        )
    }
    lines.add("way[${NotesTags.TAG_MARKER}][${NotesTags.TAG_SEVERITY}=\"breaking\"] { width: 5; }")
    lines.add(
        "node[${NotesTags.TAG_ANCHOR}] { symbol-stroke-color: #222222; symbol-stroke-width: 3; " +
            "z-index: 2500; }",
    )
    lines.add(
        "node[${NotesTags.TAG_ANCHOR}][${NotesTags.TAG_DONE}=\"yes\"] { symbol-fill-color: #9e9e9e; " +
            "text-color: #9e9e9e; opacity: 0.45; }",
    )
    lines.add(
        "node[${NotesTags.TAG_MEMBER}][${NotesTags.TAG_DONE}=\"yes\"] { symbol-fill-color: #9e9e9e; opacity: 0.35; }",
    )
    lines.add(
        "way[${NotesTags.TAG_MARKER}][${NotesTags.TAG_DONE}=\"yes\"] { color: #9e9e9e; fill-color: #9e9e9e; " +
            "opacity: 0.4; }",
    )
    return lines.joinToString("\n")
}

fun discoverNoteTypes(nodes: Collection<NoteNodeRec>, ways: Collection<NoteWayRec>): Set<String> {
    val types = LinkedHashSet(NotesTags.NOTE_TYPES)
    for (n in nodes) {
        val anchor = tagOf(n.tags, NotesTags.TAG_ANCHOR)
        val member = tagOf(n.tags, NotesTags.TAG_MEMBER)
        if (anchor == "yes" || member == "yes") {
            val t = noteType(n.tags)
            if (t.isNotEmpty()) types.add(t)
        }
    }
    for (w in ways) {
        if (tagOf(w.tags, NotesTags.TAG_MARKER) == "yes") {
            val t = noteType(w.tags)
            if (t.isNotEmpty()) types.add(t)
        }
    }
    return types
}
