package org.openstreetmap.josm.plugins.lanelet2.notes

import org.junit.jupiter.api.Assertions.assertEquals
import org.junit.jupiter.api.Assertions.assertTrue
import org.junit.jupiter.api.Test

class NotesMapCssTest {

    @Test
    fun defaultTypesMatchJythonGenerateMapcss() {
        val css = generateMapCss()
        assertTrue(css.startsWith("/* Auto-generated by notes_core.py - do not edit. */"))
        assertTrue(css.contains("meta { title: \"Lanelet2 Notes\"; }"))
        assertTrue(css.contains("node[note_anchor][note_type=\"issue\"] { symbol-fill-color: #e53935; symbol-stroke-color: #e53935; }"))
        assertTrue(css.contains("node[note_anchor][note_severity=\"breaking\"] { symbol-size: 28; }"))
        assertTrue(css.contains("way[ll2_note][note_done=\"yes\"] { color: #9e9e9e; fill-color: #9e9e9e; opacity: 0.4; }"))
        val issueIdx = css.indexOf("note_type=\"issue\"")
        val questionIdx = css.indexOf("note_type=\"question\"")
        val outdatedIdx = css.indexOf("note_type=\"outdated\"")
        assertTrue(issueIdx < questionIdx && questionIdx < outdatedIdx)
    }

    @Test
    fun extraTypesUseJythonHsvPalette() {
        val css = generateMapCss(listOf("custom_foo", "zzz"))
        assertTrue(css.contains("note_type=\"custom_foo\"] { symbol-fill-color: #f2b848; symbol-stroke-color: #f2b848; }"), css)
        assertTrue(css.contains("note_type=\"zzz\"] { symbol-fill-color: #8748f2; symbol-stroke-color: #8748f2; }"), css)
        val customIdx = css.indexOf("custom_foo")
        val zzzIdx = css.indexOf("note_type=\"zzz\"")
        assertTrue(customIdx < zzzIdx)
    }

    @Test
    fun hsvMatchesPinnedExtraColors() {
        assertEquals("#f2b848", colorForType("custom_foo", 0))
        assertEquals("#8748f2", colorForType("zzz", 1))
        assertEquals("#e53935", colorForType("issue", 99))
        assertEquals(NotesTags.DEFAULT_COLOR, colorForType("unknown", -1))
    }

    @Test
    fun discoverTypesReadsAnchorMemberAndMarker() {
        val nodes = listOf(
            NoteNodeRec(1, 0.0, 0.0, tags = mapOf(NotesTags.TAG_ANCHOR to "yes", NotesTags.TAG_TYPE to "custom_foo")),
            NoteNodeRec(2, 0.0, 0.0, tags = mapOf(NotesTags.TAG_MEMBER to "yes", NotesTags.TAG_TYPE to "zzz")),
        )
        val ways = listOf(
            NoteWayRec(3, emptyList(), tags = mapOf(NotesTags.TAG_MARKER to "yes", NotesTags.TAG_TYPE to "todo")),
        )
        val types = discoverNoteTypes(nodes, ways)
        assertTrue("custom_foo" in types)
        assertTrue("zzz" in types)
        assertTrue("todo" in types)
        assertTrue("issue" in types)
    }
}
